### ISSUE TITLE
Use wget to download dataset files

### ISSUE THREAD

**Issue by dalepotter** [IATI/iati.fetch#13]
After conversation with @andylolz it could be worth using `wget` (instead of `requests`) to download a given dataset from a publisher URL. This would therefore replace this line: https://github.com/IATI/iati.fetch/blob/fetch-dataset/iati/fetch/__init__.py#L71

@andylolz noted that, in his experience, `wget` is more resilient than `requests` when dealing with SSL certificates. Presumably large datasets would be better handled in this way, in order to reduce memory issues.

`wget` could be implemented using `subprocess.call`. Other alternatives are `urllib.urlretrieve`, [`urlgrabber`](http://urlgrabber.baseurl.org/), or even the [Python wget module](https://pypi.python.org/pypi/wget/0.3).

All these options need testing, in order to see how successful each attempt is at downloading all IATI datasets in the wild.

**Comment by andylolz** [comment]
So my goal was to be super generous and try really really hard to fetch *some data* rather than fetch *no data*. E.g. retry on timeout / forgive broken certificates etc. I found the [IATI-Registry-Refresher](https://github.com/IATI/IATI-Registry-Refresher) (which uses `wget`) did a better job than out-of-the-box `requests`.

I suspect you may be able to set up `requests` to be as forgiving (e.g. [`verify=False`](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) etc) but I gave up and used [the registry refresher](https://github.com/IATI/IATI-Registry-Refresher).

For me, best case would be to be super generous when fetching, but log warnings about broken certificates or timeouts. Because these things are potentially bad from a user perspective… But I’m still primarily interested in getting some data.

Sorry for the rambling! I hope that’s in some way useful?!

**Comment by hayfield** [comment]
If a server is configured in such a way as to mean data cannot be fetched over the transport mechanism specified in the Registry link, the dataset shouldn't be fetched.

The Registry Refresher is more forgiving because it [doesn't check certificates](https://github.com/IATI/IATI-Registry-Refresher/blob/master/fetch_data.sh#L38-L39). This should be an error (that is logged and actioned in some way such as notifying the publisher) since not checking SSL certificates is a bad idea.

**Comment by andylolz** [comment]
> If a server is configured in such a way as to mean data cannot be fetched over the transport mechanism specified in the Registry link, the dataset shouldn't be fetched.

Totally depends on use case IMO. For my own use case, I need to be super generous. Publishers shouldn’t score zero on an index just because their cert is broken. They should be informed of it; maybe they should be marked down for it… But refusing to fetch and assess data means all other feedback on data quality is blocked until the cert issue is fixed.

[Of course there’s a risk I’m assessing the data of some man-in-the-middle attacker! But in all likelihood, the server is just incorrectly configured / the cert has expired.]

So I guess here, it depends who the intended users of [iati.fetch](https://github.com/IATI/iati.fetch) are.

NB I raised another use case where it might actually be preferable not to be too strict about SSL certs here: IATI/IATI-Datastore#264. That’s also (kiiind of) supported by the fact the datastore isn’t served over SSL anyway (IATI/IATI-Datastore#256).

> The Registry Refresher is more forgiving because it doesn't check certificates.

Yeah, that’s one of the reasons. But also, retries and timeouts are more generous than default `requests`.
